export const TRIBES = [	
	"Absentee Shawnee Tribe of Indians of Oklahoma",
	"Alabama-Quassarte Tribal Town",
	"Apache Tribe of Oklahoma",
	"Caddo Nation of Oklahoma",
	"Cherokee Nation",
	"Cheyenne and Arapaho Tribes",
	"Chickasaw Nation, The",
	"Choctaw Nation of Oklahoma",
	"Citizen Potawatomi Nation",
	"Comanche Nation",
	"Delaware Nation",
	"Delaware Tribe of Indians",
	"Eastern Shawnee Tribe of Oklahoma",
	"Euchee (Yuchi) Tribe of Indians",
	"Fort Sill Apache Tribe of Oklahoma",
	"Iowa Tribe of Oklahoma",
	"Kaw Nation",
	"Kialegee Tribal Town",
	"Kickapoo Tribe of Oklahoma",
	"Kiowa Indian Tribe of Oklahoma",
	"Miami Tribe of Oklahoma",
	"Modoc Nation",
	"Muscogee (Creek) Nation",
	"Osage Nation",
	"Otoe-Missouria Tribe of Indians",
	"Ottawa Tribe of Oklahoma",
	"Pawnee Nation of Oklahoma",
	"Peoria Tribe of Indians of Oklahoma",
	"Ponca Tribe of Indians of Oklahoma",
	"Quapaw Nation (Quapaw Tribe of Indians)",
	"Sac and Fox Nation",
	"Seminole Nation of Oklahoma",
	"Seneca-Cayuga Nation",
	"Shawnee Tribe",
	"Thlopthlocco Tribal Town",
	"Tonkawa Tribe of Indians of Oklahoma",
	"United Keetoowah Band of Cherokee Indians in Oklahoma",
	"Wichita and Affiliated Tribes",
];	