import type { HumanNeedId } from "./types";

export const INTENT_SYNONYMS: Record<string, HumanNeedId[]> = {
  apartment: ["housing"],
  apartments: ["housing"],
  shelter: ["housing"],
  rent: ["housing", "utilities"],
  rental: ["housing", "utilities"],
  landlord: ["housing", "legal"],
  eviction: ["housing", "legal"],
  evicted: ["housing", "legal"],
  homeless: ["housing"],
  homelessness: ["housing"],
  housing: ["housing"],

  groceries: ["food"],
  grocery: ["food"],
  meals: ["food"],
  meal: ["food"],
  pantry: ["food"],
  "food bank": ["food"],
  food: ["food"],

  electric: ["utilities"],
  electricity: ["utilities"],
  gas: ["utilities"],
  "gas bill": ["utilities"],
  water: ["utilities"],
  "water bill": ["utilities"],
  utilities: ["utilities"],
  "utility bill": ["utilities"],

  hospital: ["healthcare"],
  hospitals: ["healthcare"],
  er: ["healthcare", "crisis"],
  "emergency room": ["healthcare", "crisis"],
  emergency: ["healthcare", "crisis"],
  "urgent care": ["healthcare"],
  doctor: ["healthcare"],
  doctors: ["healthcare"],
  physician: ["healthcare"],
  physicians: ["healthcare"],
  clinic: ["healthcare"],
  dentist: ["healthcare"],
  dental: ["healthcare"],
  medical: ["healthcare"],
  "medical center": ["healthcare"],
  surgery: ["healthcare"],
  imaging: ["healthcare"],
  "x ray": ["healthcare"],
  xray: ["healthcare"],
  mri: ["healthcare"],
  healthcare: ["healthcare"],

  counseling: ["mental_health"],
  counselor: ["mental_health"],
  counselors: ["mental_health"],
  therapist: ["mental_health"],
  therapists: ["mental_health"],
  therapy: ["mental_health"],
  psychologist: ["mental_health"],
  psychologists: ["mental_health"],
  psychiatry: ["mental_health"],
  psychiatrist: ["mental_health"],
  psychiatric: ["mental_health"],
  depression: ["mental_health"],
  anxiety: ["mental_health"],
  "behavioral health": ["mental_health"],
  "mental health clinic": ["mental_health"],
  "mental health": ["mental_health"],

  addiction: ["substance_use"],
  addicted: ["substance_use"],
  rehab: ["substance_use"],
  rehabilitation: ["substance_use"],
  detox: ["substance_use"],
  recovery: ["substance_use"],
  "sober living": ["substance_use"],
  "substance abuse": ["substance_use"],
  substance: ["substance_use"],
  treatment: ["substance_use"],

  bus: ["transportation"],
  buses: ["transportation"],
  ride: ["transportation"],
  rides: ["transportation"],
  vehicle: ["transportation"],
  "gas voucher": ["transportation"],
  transportation: ["transportation"],

  lawyer: ["legal"],
  lawyers: ["legal"],
  attorney: ["legal"],
  attorneys: ["legal"],
  court: ["legal"],
  custody: ["legal"],
  legal: ["legal"],

  job: ["employment"],
  jobs: ["employment"],
  work: ["employment"],
  resume: ["employment"],
  interview: ["employment"],
  training: ["employment"],
  employment: ["employment"],

  benefits: ["financial_assistance"],
  cash: ["financial_assistance"],
  financial: ["financial_assistance"],

  daycare: ["childcare"],
  childcare: ["childcare"],
  "child care": ["childcare"],

  parenting: ["family_support"],
  caregiver: ["family_support"],
  family: ["family_support"],

  teen: ["youth"],
  youth: ["youth"],
  children: ["youth", "childcare"],

  abuse: ["safety"],
  violence: ["safety"],
  safety: ["safety"],

  crisis: ["crisis"],
  hotline: ["crisis"],

  native: ["tribal_services"],
  tribal: ["tribal_services"],
  tribe: ["tribal_services"],
};
